spring:
  profiles:
    active: local
  application:
    name: aegis-server
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
  session:
    redis:
      namespace: aegis:session
    timeout: ${SESSION_TIMEOUT}

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    url: /docs/api
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /docs/api
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

exception:
  log-only-aegis-stack-trace: ${LOG_ONLY_AEGIS_STACK_TRACE}

email-restriction:
  enabled: ${EMAIL_RESTRICTION_ENABLED}

server:
  forward-headers-strategy: framework

payment:
  bank-type: ibk

time:
  zone: Asia/Seoul

internal-api-key:
  tx-track-api: ${TRANSACTION_TRACK_API_KEY}

discord:
  token: ${DISCORD_BOT_TOKEN}
  guild-id: ${DISCORD_GUILD_ID}
  alarm-channel-id: ${DISCORD_ALARM_CHANNEL_ID}
  complete-role-id: ${DISCORD_COMPLETE_ROLE_ID}

google:
  credentials:
    json: ${GOOGLE_CREDENTIALS_JSON}
  spreadsheets:
    id: ${GOOGLE_SPREADSHEET_ID}
