spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL}
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
