name: Build Spring Boot Application - GitHub Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Gradle
        run: ./gradlew build
